name: CD - Deploy to dev

on:
  push:
    branches:
      - dev-i

jobs:
  deploy-qa:
    uses: ops-migration/central-shared-workflow/.github/workflows/cd-workflow.yml@main
    with:
      aws-region: "us-east-1"
